//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfinx.App.Shared.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LockLanguageResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LockLanguageResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sfinx.App.Shared.Languages.LockLanguageResources_en", typeof(LockLanguageResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LockEdit_Title {
            get {
                return ResourceManager.GetString("LockEdit/Title", resourceCulture);
            }
        }
        
        internal static string LockEdit_Subtitle {
            get {
                return ResourceManager.GetString("LockEdit/Subtitle", resourceCulture);
            }
        }
        
        internal static string LockEdit_Manage {
            get {
                return ResourceManager.GetString("LockEdit/Manage", resourceCulture);
            }
        }
        
        internal static string Locks_Patience {
            get {
                return ResourceManager.GetString("Locks/Patience", resourceCulture);
            }
        }
        
        internal static string Locks_Subtitle {
            get {
                return ResourceManager.GetString("Locks/Subtitle", resourceCulture);
            }
        }
        
        internal static string Locks_Title {
            get {
                return ResourceManager.GetString("Locks/Title", resourceCulture);
            }
        }
        
        internal static string LockEdit_Patience {
            get {
                return ResourceManager.GetString("LockEdit/Patience", resourceCulture);
            }
        }
        
        internal static string Keys_GenerateKey {
            get {
                return ResourceManager.GetString("Keys/GenerateKey", resourceCulture);
            }
        }
        
        internal static string KeyLabel {
            get {
                return ResourceManager.GetString("KeyLabel", resourceCulture);
            }
        }
        
        internal static string KeyOneTime {
            get {
                return ResourceManager.GetString("KeyOneTime", resourceCulture);
            }
        }
        
        internal static string KeyGenerationSuccess {
            get {
                return ResourceManager.GetString("KeyGenerationSuccess", resourceCulture);
            }
        }
        
        internal static string ActivityLog {
            get {
                return ResourceManager.GetString("ActivityLog", resourceCulture);
            }
        }
        
        internal static string UpdateLockSuccess {
            get {
                return ResourceManager.GetString("UpdateLockSuccess", resourceCulture);
            }
        }
        
        internal static string Permissions_Patience {
            get {
                return ResourceManager.GetString("Permissions/Patience", resourceCulture);
            }
        }
        
        internal static string Keys_Patience {
            get {
                return ResourceManager.GetString("Keys/Patience", resourceCulture);
            }
        }
        
        internal static string Keys_Subtitle {
            get {
                return ResourceManager.GetString("Keys/Subtitle", resourceCulture);
            }
        }
        
        internal static string Key_Patience {
            get {
                return ResourceManager.GetString("Key/Patience", resourceCulture);
            }
        }
        
        internal static string Keys_Title {
            get {
                return ResourceManager.GetString("Keys/Title", resourceCulture);
            }
        }
        
        internal static string Confirm_OpenLock {
            get {
                return ResourceManager.GetString("Confirm/OpenLock", resourceCulture);
            }
        }
        
        internal static string KeyEdit_Title {
            get {
                return ResourceManager.GetString("KeyEdit/Title", resourceCulture);
            }
        }
        
        internal static string You_own_this_lock {
            get {
                return ResourceManager.GetString("You own this lock", resourceCulture);
            }
        }
        
        internal static string NoKeysFoundOwner {
            get {
                return ResourceManager.GetString("NoKeysFoundOwner", resourceCulture);
            }
        }
        
        internal static string NoKeysFoundUser {
            get {
                return ResourceManager.GetString("NoKeysFoundUser", resourceCulture);
            }
        }
        
        internal static string OwnedBy {
            get {
                return ResourceManager.GetString("OwnedBy", resourceCulture);
            }
        }
        
        internal static string LockStatus_Unlocked {
            get {
                return ResourceManager.GetString("LockStatus/Unlocked", resourceCulture);
            }
        }
        
        internal static string LockStatus_Unknown {
            get {
                return ResourceManager.GetString("LockStatus/Unknown", resourceCulture);
            }
        }
        
        internal static string LockStatus_Locked {
            get {
                return ResourceManager.GetString("LockStatus/Locked", resourceCulture);
            }
        }
        
        internal static string BatteryMessage {
            get {
                return ResourceManager.GetString("BatteryMessage", resourceCulture);
            }
        }
        
        internal static string LockErrorConnection {
            get {
                return ResourceManager.GetString("LockErrorConnection", resourceCulture);
            }
        }
        
        internal static string LockStatus_Unkown {
            get {
                return ResourceManager.GetString("LockStatus/Unkown", resourceCulture);
            }
        }
        
        internal static string LockAuth {
            get {
                return ResourceManager.GetString("LockAuth", resourceCulture);
            }
        }
        
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string Relink {
            get {
                return ResourceManager.GetString("Relink", resourceCulture);
            }
        }
        
        internal static string You_are_not_the_owner_of_the_lock {
            get {
                return ResourceManager.GetString("You are not the owner of the lock", resourceCulture);
            }
        }
        
        internal static string Register_new_lock {
            get {
                return ResourceManager.GetString("Register new lock", resourceCulture);
            }
        }
        
        internal static string Retrieve_locks {
            get {
                return ResourceManager.GetString("Retrieve locks", resourceCulture);
            }
        }
        
        internal static string Make_sure_the_authorization_is_completed_before_retrieving_your_locks_ {
            get {
                return ResourceManager.GetString("Make sure the authorization is completed before retrieving your locks.", resourceCulture);
            }
        }
        
        internal static string Connected_Lock_Types {
            get {
                return ResourceManager.GetString("Connected Lock Types", resourceCulture);
            }
        }
        
        internal static string No_lock_types_connected {
            get {
                return ResourceManager.GetString("No lock types connected", resourceCulture);
            }
        }
        
        internal static string Confirm_RevokeVendorAccess {
            get {
                return ResourceManager.GetString("Confirm/RevokeVendorAccess", resourceCulture);
            }
        }
        
        internal static string LockAuth_NotFound {
            get {
                return ResourceManager.GetString("LockAuth/NotFound", resourceCulture);
            }
        }
        
        internal static string LockAuth_Valid {
            get {
                return ResourceManager.GetString("LockAuth/Valid", resourceCulture);
            }
        }
        
        internal static string LockAuth_Invalid {
            get {
                return ResourceManager.GetString("LockAuth/Invalid", resourceCulture);
            }
        }
        
        internal static string LockAuth_Expired {
            get {
                return ResourceManager.GetString("LockAuth/Expired", resourceCulture);
            }
        }
        
        internal static string LockAuth_Unknown {
            get {
                return ResourceManager.GetString("LockAuth/Unknown", resourceCulture);
            }
        }
        
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        internal static string VendorAuthorizationStatus_Title {
            get {
                return ResourceManager.GetString("VendorAuthorizationStatus/Title", resourceCulture);
            }
        }
        
        internal static string Confirm_DeleteLock {
            get {
                return ResourceManager.GetString("Confirm/DeleteLock", resourceCulture);
            }
        }
        
        internal static string Remove_lock {
            get {
                return ResourceManager.GetString("Remove lock", resourceCulture);
            }
        }
        
        internal static string Add_simulated_lock {
            get {
                return ResourceManager.GetString("Add simulated lock", resourceCulture);
            }
        }
        
        internal static string KeyEdit_Patience {
            get {
                return ResourceManager.GetString("KeyEdit/Patience", resourceCulture);
            }
        }
        
        internal static string Add_key {
            get {
                return ResourceManager.GetString("Add key", resourceCulture);
            }
        }
        
        internal static string Keys_AssignKey {
            get {
                return ResourceManager.GetString("Keys/AssignKey", resourceCulture);
            }
        }
        
        internal static string KeyPermission_Reference {
            get {
                return ResourceManager.GetString("KeyPermission/Reference", resourceCulture);
            }
        }
        
        internal static string KeyPermission_FreeText {
            get {
                return ResourceManager.GetString("KeyPermission/FreeText", resourceCulture);
            }
        }
        
        internal static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        internal static string KeySuccessfullyAssigned {
            get {
                return ResourceManager.GetString("KeySuccessfullyAssigned", resourceCulture);
            }
        }
        
        internal static string KeyAssignmentFailed {
            get {
                return ResourceManager.GetString("KeyAssignmentFailed", resourceCulture);
            }
        }
        
        internal static string Find_lock_by_reference {
            get {
                return ResourceManager.GetString("Find lock by reference", resourceCulture);
            }
        }
        
        internal static string LockNotFound {
            get {
                return ResourceManager.GetString("LockNotFound", resourceCulture);
            }
        }
        
        internal static string Confirm_CloseLock {
            get {
                return ResourceManager.GetString("Confirm/CloseLock", resourceCulture);
            }
        }
        
        internal static string ManageLocks {
            get {
                return ResourceManager.GetString("ManageLocks", resourceCulture);
            }
        }
    }
}
