//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfinx.App.Shared.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardLanguageResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardLanguageResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sfinx.App.Shared.Languages.WizardLanguageResources_en", typeof(WizardLanguageResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Set_up_Sfinx {
            get {
                return ResourceManager.GetString("Set up Sfinx", resourceCulture);
            }
        }
        
        internal static string Install_your_lock {
            get {
                return ResourceManager.GetString("Install your lock", resourceCulture);
            }
        }
        
        internal static string Link_lock_account {
            get {
                return ResourceManager.GetString("Link lock account", resourceCulture);
            }
        }
        
        internal static string Select_your_lock {
            get {
                return ResourceManager.GetString("Select your lock", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string Set_up_your_smartlock {
            get {
                return ResourceManager.GetString("Set up your smartlock", resourceCulture);
            }
        }
        
        internal static string Invitation_code {
            get {
                return ResourceManager.GetString("Invitation code", resourceCulture);
            }
        }
        
        internal static string If_you_have_received_an_invitation_code__please_validate_it_below_ {
            get {
                return ResourceManager.GetString("If you have received an invitation code, please validate it below.", resourceCulture);
            }
        }
        
        internal static string Enter_validation_code {
            get {
                return ResourceManager.GetString("Enter validation code", resourceCulture);
            }
        }
        
        internal static string Validate_code {
            get {
                return ResourceManager.GetString("Validate code", resourceCulture);
            }
        }
        
        internal static string Invitation_code_successfully_validated {
            get {
                return ResourceManager.GetString("Invitation code successfully validated", resourceCulture);
            }
        }
        
        internal static string Invitation_code_is_not_valid_or_expired {
            get {
                return ResourceManager.GetString("Invitation code is not valid or expired", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Itsme_integration_coming_soon {
            get {
                return ResourceManager.GetString("Itsme integration coming soon", resourceCulture);
            }
        }
        
        internal static string Set_up_your_Sfinx_account {
            get {
                return ResourceManager.GetString("Set up your Sfinx account", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string Select_an_existing_lock_from_the_list_or_register_a_new_lock {
            get {
                return ResourceManager.GetString("Select an existing lock from the list or register a new lock", resourceCulture);
            }
        }
        
        internal static string Select_the_brand {
            get {
                return ResourceManager.GetString("Select the brand", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string Specify_Lock {
            get {
                return ResourceManager.GetString("Specify Lock", resourceCulture);
            }
        }
        
        internal static string Lock_type_selection {
            get {
                return ResourceManager.GetString("Lock type selection", resourceCulture);
            }
        }
        
        internal static string foodbag_OrganizationName {
            get {
                return ResourceManager.GetString("foodbag/OrganizationName", resourceCulture);
            }
        }
        
        internal static string foodbag_ProjectName {
            get {
                return ResourceManager.GetString("foodbag/ProjectName", resourceCulture);
            }
        }
        
        internal static string foodbag_WelcomeText {
            get {
                return ResourceManager.GetString("foodbag/WelcomeText", resourceCulture);
            }
        }
        
        internal static string foodbag_SfinxRegistrationText {
            get {
                return ResourceManager.GetString("foodbag/SfinxRegistrationText", resourceCulture);
            }
        }
        
        internal static string sfinx_OrganizationName {
            get {
                return ResourceManager.GetString("sfinx/OrganizationName", resourceCulture);
            }
        }
        
        internal static string sfinx_ProjectName {
            get {
                return ResourceManager.GetString("sfinx/ProjectName", resourceCulture);
            }
        }
        
        internal static string sfinx_WelcomeText {
            get {
                return ResourceManager.GetString("sfinx/WelcomeText", resourceCulture);
            }
        }
        
        internal static string sfinx_SfinxRegistrationText {
            get {
                return ResourceManager.GetString("sfinx/SfinxRegistrationText", resourceCulture);
            }
        }
        
        internal static string Register_a_new_lock {
            get {
                return ResourceManager.GetString("Register a new lock", resourceCulture);
            }
        }
        
        internal static string Retrieving_supported_locks {
            get {
                return ResourceManager.GetString("Retrieving supported locks", resourceCulture);
            }
        }
        
        internal static string Retrieving_supported_products {
            get {
                return ResourceManager.GetString("Retrieving supported products", resourceCulture);
            }
        }
        
        internal static string Choose_your_lock {
            get {
                return ResourceManager.GetString("Choose your lock", resourceCulture);
            }
        }
        
        internal static string Make_sure_your_lock_is_installed_correctly {
            get {
                return ResourceManager.GetString("Make sure your lock is installed correctly", resourceCulture);
            }
        }
        
        internal static string install_01 {
            get {
                return ResourceManager.GetString("install-01", resourceCulture);
            }
        }
        
        internal static string install_02 {
            get {
                return ResourceManager.GetString("install-02", resourceCulture);
            }
        }
        
        internal static string install_03 {
            get {
                return ResourceManager.GetString("install-03", resourceCulture);
            }
        }
        
        internal static string install_04 {
            get {
                return ResourceManager.GetString("install-04", resourceCulture);
            }
        }
        
        internal static string My_lock_is_installed_correctly {
            get {
                return ResourceManager.GetString("My lock is installed correctly", resourceCulture);
            }
        }
        
        internal static string Connect_your_account_to_Sfinx {
            get {
                return ResourceManager.GetString("Connect your account to Sfinx", resourceCulture);
            }
        }
        
        internal static string Give_authorization_to_Sfinx_to_use_your_smart_lock {
            get {
                return ResourceManager.GetString("Give authorization to Sfinx to use your smart lock", resourceCulture);
            }
        }
        
        internal static string Creating_login_link {
            get {
                return ResourceManager.GetString("Creating login link", resourceCulture);
            }
        }
        
        internal static string Connect_account {
            get {
                return ResourceManager.GetString("Connect account", resourceCulture);
            }
        }
        
        internal static string You_will_be_taken_to_the_log_in_page_of {
            get {
                return ResourceManager.GetString("You will be taken to the log-in page of", resourceCulture);
            }
        }
        
        internal static string Select_a_lock {
            get {
                return ResourceManager.GetString("Select a lock", resourceCulture);
            }
        }
        
        internal static string Configure_your_lock {
            get {
                return ResourceManager.GetString("Configure your lock", resourceCulture);
            }
        }
        
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        internal static string Register_your_lock {
            get {
                return ResourceManager.GetString("Register your lock", resourceCulture);
            }
        }
        
        internal static string Retrieving_your_locks_from_the_vendor {
            get {
                return ResourceManager.GetString("Retrieving your locks from the vendor", resourceCulture);
            }
        }
        
        internal static string A_friendly_name_for_you_to_identify_the_lock {
            get {
                return ResourceManager.GetString("A friendly name for you to identify the lock", resourceCulture);
            }
        }
        
        internal static string An_optional_description {
            get {
                return ResourceManager.GetString("An optional description", resourceCulture);
            }
        }
        
        internal static string The_unique_id_of_your_lock {
            get {
                return ResourceManager.GetString("The unique id of your lock", resourceCulture);
            }
        }
        
        internal static string Reference_linking_your_lock_to_the_provider {
            get {
                return ResourceManager.GetString("Reference linking your lock to the provider", resourceCulture);
            }
        }
        
        internal static string CompletionMessage {
            get {
                return ResourceManager.GetString("CompletionMessage", resourceCulture);
            }
        }
        
        internal static string See_your_locks {
            get {
                return ResourceManager.GetString("See your locks", resourceCulture);
            }
        }
        
        internal static string foodbag_CompletionText {
            get {
                return ResourceManager.GetString("foodbag/CompletionText", resourceCulture);
            }
        }
        
        internal static string sfinx_CompletionText {
            get {
                return ResourceManager.GetString("sfinx/CompletionText", resourceCulture);
            }
        }
        
        internal static string You_are_all_set_up {
            get {
                return ResourceManager.GetString("You are all set up", resourceCulture);
            }
        }
        
        internal static string MemberWelcome {
            get {
                return ResourceManager.GetString("MemberWelcome", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string MemberGuidance {
            get {
                return ResourceManager.GetString("MemberGuidance", resourceCulture);
            }
        }
        
        internal static string Security_setup {
            get {
                return ResourceManager.GetString("Security setup", resourceCulture);
            }
        }
        
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        internal static string MemberGuidance2 {
            get {
                return ResourceManager.GetString("MemberGuidance2", resourceCulture);
            }
        }
        
        internal static string MemberCompletionMessage {
            get {
                return ResourceManager.GetString("MemberCompletionMessage", resourceCulture);
            }
        }
        
        internal static string ProfileCompletion {
            get {
                return ResourceManager.GetString("ProfileCompletion", resourceCulture);
            }
        }
        
        internal static string Playground_Title {
            get {
                return ResourceManager.GetString("Playground/Title", resourceCulture);
            }
        }
        
        internal static string Add_permission {
            get {
                return ResourceManager.GetString("Add permission", resourceCulture);
            }
        }
    }
}
